name: Publish to NPM

on:
  release:
    types: [published]

env:
  NODE_VERSION: '16.18.0'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: 'Resolve Project Dependencies Using NPM'
        shell: bash
        run: |
          pushd .
          npm install
          popd

      - name: Build app
        run: npm run build

      - name: Submit app
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
