on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        if: '! github.event.pull_request.head.repo.fork '
        with:
          release-type: node
          package-name: react-material-symbols
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}